name: 'Kafka E2E Tests'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/modules/kafka/**'

concurrency:
  group: kafka-tests-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  e2e:
    name: 'Kafka E2E'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 45

    defaults:
      run:
        working-directory: ./terraform/modules/kafka

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v4

    - name: Azure Login
      timeout-minutes: 1
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      timeout-minutes: 1
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      timeout-minutes: 3
      run: terraform init -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Run Kafka E2E Test
      timeout-minutes: 35
      run: terraform test -filter=tests/e2e.tftest.hcl -no-color
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true
